"""initial schema

Revision ID: 50d7c5d998ec
Revises:
Create Date: 2026-10-02 13:03:28.278005

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "50d7c5d998ec"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content",
        sa.Column("content_id", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("audience", sa.String(length=16), nullable=False),
        sa.Column("action_type", sa.String(length=32), nullable=False),
        sa.Column("topic", sa.String(length=64), nullable=False),
        sa.Column("measure", sa.String(length=32), nullable=True),
        sa.Column("specialty", sa.String(length=64), nullable=True),
        sa.Column("channels", sa.JSON(), nullable=False),
        sa.Column("mlr_status", sa.String(length=16), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("content_id", name=op.f("pk_content")),
    )
    with op.batch_alter_table("content", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_content_audience"), ["audience"], unique=False)
        batch_op.create_index(batch_op.f("ix_content_mlr_status"), ["mlr_status"], unique=False)

    op.create_table(
        "engine_config",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_ts", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_engine_config")),
    )
    op.create_table(
        "engine_cycle",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("started_ts", sa.DateTime(), nullable=False),
        sa.Column("finished_ts", sa.DateTime(), nullable=True),
        sa.Column("stats", sa.JSON(none_as_null=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_engine_cycle")),
    )
    op.create_table(
        "feature_snapshot",
        sa.Column("target_type", sa.String(length=8), nullable=False),
        sa.Column("target_id", sa.String(length=16), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint(
            "target_type", "target_id", "as_of_date", name=op.f("pk_feature_snapshot")
        ),
    )
    op.create_table(
        "hcp",
        sa.Column("hcp_id", sa.String(length=16), nullable=False),
        sa.Column("npi", sa.String(length=10), nullable=False),
        sa.Column("first_name", sa.String(length=64), nullable=False),
        sa.Column("last_name", sa.String(length=64), nullable=False),
        sa.Column("specialty", sa.String(length=64), nullable=False),
        sa.Column("taxonomy_code", sa.String(length=16), nullable=False),
        sa.Column("organization", sa.String(length=128), nullable=False),
        sa.Column("city", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("zip", sa.String(length=10), nullable=False),
        sa.Column("rx_volume_annual", sa.Integer(), nullable=False),
        sa.Column("segment", sa.String(length=32), nullable=True),
        sa.Column("value_score", sa.Float(), nullable=True),
        sa.Column("channel_affinity", sa.String(length=16), nullable=True),
        sa.PrimaryKeyConstraint("hcp_id", name=op.f("pk_hcp")),
        sa.UniqueConstraint("npi", name=op.f("uq_hcp_npi")),
    )
    with op.batch_alter_table("hcp", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_hcp_segment"), ["segment"], unique=False)
        batch_op.create_index(batch_op.f("ix_hcp_specialty"), ["specialty"], unique=False)

    op.create_table(
        "model_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("algorithm", sa.String(length=64), nullable=False),
        sa.Column("trained_ts", sa.DateTime(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("artifact_path", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_version")),
    )
    with op.batch_alter_table("model_version", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_model_version_name"), ["name"], unique=False)

    op.create_table(
        "patient",
        sa.Column("patient_id", sa.String(length=16), nullable=False),
        sa.Column("first_name", sa.String(length=64), nullable=False),
        sa.Column("last_name", sa.String(length=64), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("sex", sa.String(length=1), nullable=False),
        sa.Column("city", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("zip", sa.String(length=10), nullable=False),
        sa.Column("plan_type", sa.String(length=32), nullable=False),
        sa.Column("preferred_channel", sa.String(length=16), nullable=True),
        sa.Column("risk_segment", sa.String(length=16), nullable=True),
        sa.PrimaryKeyConstraint("patient_id", name=op.f("pk_patient")),
    )
    with op.batch_alter_table("patient", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_patient_risk_segment"), ["risk_segment"], unique=False)

    op.create_table(
        "sim_latent",
        sa.Column("target_type", sa.String(length=8), nullable=False),
        sa.Column("target_id", sa.String(length=16), nullable=False),
        sa.Column("traits", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("target_type", "target_id", name=op.f("pk_sim_latent")),
    )
    op.create_table(
        "consent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.String(length=16), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=True),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patient.patient_id"], name=op.f("fk_consent_patient_id_patient")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consent")),
    )
    with op.batch_alter_table("consent", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_consent_patient_id"), ["patient_id"], unique=False)

    op.create_table(
        "patient_hcp",
        sa.Column("patient_id", sa.String(length=16), nullable=False),
        sa.Column("hcp_id", sa.String(length=16), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["hcp_id"], ["hcp.hcp_id"], name=op.f("fk_patient_hcp_hcp_id_hcp")),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patient.patient_id"], name=op.f("fk_patient_hcp_patient_id_patient")
        ),
        sa.PrimaryKeyConstraint("patient_id", "hcp_id", name=op.f("pk_patient_hcp")),
    )
    with op.batch_alter_table("patient_hcp", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_patient_hcp_hcp_id"), ["hcp_id"], unique=False)

    op.create_table(
        "patient_therapy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.String(length=16), nullable=False),
        sa.Column("measure", sa.String(length=32), nullable=False),
        sa.Column("drug_name", sa.String(length=64), nullable=False),
        sa.Column("rxnorm", sa.String(length=16), nullable=True),
        sa.Column("prescriber_hcp_id", sa.String(length=16), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("days_supply", sa.Integer(), nullable=False),
        sa.Column("copay", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.patient_id"],
            name=op.f("fk_patient_therapy_patient_id_patient"),
        ),
        sa.ForeignKeyConstraint(
            ["prescriber_hcp_id"],
            ["hcp.hcp_id"],
            name=op.f("fk_patient_therapy_prescriber_hcp_id_hcp"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patient_therapy")),
    )
    with op.batch_alter_table("patient_therapy", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_patient_therapy_measure"), ["measure"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_patient_therapy_patient_id"), ["patient_id"], unique=False
        )

    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("hcp_id", sa.String(length=16), nullable=True),
        sa.Column("patient_id", sa.String(length=16), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["hcp_id"], ["hcp.hcp_id"], name=op.f("fk_user_hcp_id_hcp")),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patient.patient_id"], name=op.f("fk_user_patient_id_patient")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("username", name=op.f("uq_user_username")),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_role"), ["role"], unique=False)

    op.create_table(
        "adherence_snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.String(length=16), nullable=False),
        sa.Column("therapy_id", sa.Integer(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("pdc", sa.Float(), nullable=False),
        sa.Column("mpr", sa.Float(), nullable=False),
        sa.Column("last_fill_date", sa.Date(), nullable=True),
        sa.Column("gap_days", sa.Integer(), nullable=False),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column("risk_segment", sa.String(length=16), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.patient_id"],
            name=op.f("fk_adherence_snapshot_patient_id_patient"),
        ),
        sa.ForeignKeyConstraint(
            ["therapy_id"],
            ["patient_therapy.id"],
            name=op.f("fk_adherence_snapshot_therapy_id_patient_therapy"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_adherence_snapshot")),
    )
    with op.batch_alter_table("adherence_snapshot", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_adherence_snapshot_patient_id"), ["patient_id"], unique=False
        )
        batch_op.create_index(
            "ix_adherence_snapshot_therapy_asof", ["therapy_id", "as_of_date"], unique=False
        )

    op.create_table(
        "care_manager_patient",
        sa.Column("care_manager_user_id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["care_manager_user_id"],
            ["user.id"],
            name=op.f("fk_care_manager_patient_care_manager_user_id_user"),
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.patient_id"],
            name=op.f("fk_care_manager_patient_patient_id_patient"),
        ),
        sa.PrimaryKeyConstraint(
            "care_manager_user_id", "patient_id", name=op.f("pk_care_manager_patient")
        ),
    )
    with op.batch_alter_table("care_manager_patient", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_care_manager_patient_patient_id"), ["patient_id"], unique=False
        )

    op.create_table(
        "content_review",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.String(length=16), nullable=False),
        sa.Column("reviewer_user_id", sa.Integer(), nullable=True),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content.content_id"],
            name=op.f("fk_content_review_content_id_content"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_user_id"], ["user.id"], name=op.f("fk_content_review_reviewer_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_review")),
    )
    with op.batch_alter_table("content_review", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_content_review_content_id"), ["content_id"], unique=False
        )

    op.create_table(
        "medication_fill",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.String(length=16), nullable=False),
        sa.Column("therapy_id", sa.Integer(), nullable=False),
        sa.Column("drug_name", sa.String(length=64), nullable=False),
        sa.Column("fill_date", sa.Date(), nullable=False),
        sa.Column("days_supply", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("copay", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.patient_id"],
            name=op.f("fk_medication_fill_patient_id_patient"),
        ),
        sa.ForeignKeyConstraint(
            ["therapy_id"],
            ["patient_therapy.id"],
            name=op.f("fk_medication_fill_therapy_id_patient_therapy"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medication_fill")),
    )
    with op.batch_alter_table("medication_fill", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_medication_fill_patient_id"), ["patient_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_medication_fill_therapy_id"), ["therapy_id"], unique=False
        )

    op.create_table(
        "nba",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=False),
        sa.Column("target_type", sa.String(length=8), nullable=False),
        sa.Column("target_id", sa.String(length=16), nullable=False),
        sa.Column("therapy_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("scheduled_for", sa.Date(), nullable=False),
        sa.Column("timing_note", sa.String(length=200), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("rationale_summary", sa.Text(), nullable=True),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.Column("content_id", sa.String(length=16), nullable=True),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("priority", sa.Float(), nullable=False),
        sa.Column("predicted", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("withheld", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("block_reason", sa.Text(), nullable=True),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("created_ts", sa.DateTime(), nullable=False),
        sa.Column("reviewed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("reviewed_ts", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_id"], ["content.content_id"], name=op.f("fk_nba_content_id_content")
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"], ["engine_cycle.id"], name=op.f("fk_nba_cycle_id_engine_cycle")
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"], ["user.id"], name=op.f("fk_nba_reviewed_by_user_id_user")
        ),
        sa.ForeignKeyConstraint(
            ["therapy_id"], ["patient_therapy.id"], name=op.f("fk_nba_therapy_id_patient_therapy")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nba")),
    )
    with op.batch_alter_table("nba", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_nba_cycle_id"), ["cycle_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_nba_status"), ["status"], unique=False)
        batch_op.create_index("ix_nba_target", ["target_type", "target_id"], unique=False)

    op.create_table(
        "rep_hcp",
        sa.Column("rep_user_id", sa.Integer(), nullable=False),
        sa.Column("hcp_id", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["hcp_id"], ["hcp.hcp_id"], name=op.f("fk_rep_hcp_hcp_id_hcp")),
        sa.ForeignKeyConstraint(
            ["rep_user_id"], ["user.id"], name=op.f("fk_rep_hcp_rep_user_id_user")
        ),
        sa.PrimaryKeyConstraint("rep_user_id", "hcp_id", name=op.f("pk_rep_hcp")),
    )
    with op.batch_alter_table("rep_hcp", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rep_hcp_hcp_id"), ["hcp_id"], unique=False)

    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("nba_id", sa.Integer(), nullable=True),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=48), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("actor_role", sa.String(length=32), nullable=False),
        sa.Column("compliance_ok", sa.Boolean(), nullable=True),
        sa.Column("consent_ok", sa.Boolean(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("detail", sa.JSON(none_as_null=True), nullable=True),
        sa.ForeignKeyConstraint(["nba_id"], ["nba.id"], name=op.f("fk_audit_log_nba_id_nba")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_nba_id"), ["nba_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_ts"), ["ts"], unique=False)

    op.create_table(
        "interaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_type", sa.String(length=8), nullable=False),
        sa.Column("target_id", sa.String(length=16), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("int_ts", sa.DateTime(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("outcome_ts", sa.DateTime(), nullable=True),
        sa.Column("content_id", sa.String(length=16), nullable=True),
        sa.Column("therapy_id", sa.Integer(), nullable=True),
        sa.Column("nba_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["user.id"], name=op.f("fk_interaction_actor_user_id_user")
        ),
        sa.ForeignKeyConstraint(
            ["content_id"], ["content.content_id"], name=op.f("fk_interaction_content_id_content")
        ),
        sa.ForeignKeyConstraint(["nba_id"], ["nba.id"], name=op.f("fk_interaction_nba_id_nba")),
        sa.ForeignKeyConstraint(
            ["therapy_id"],
            ["patient_therapy.id"],
            name=op.f("fk_interaction_therapy_id_patient_therapy"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interaction")),
    )
    with op.batch_alter_table("interaction", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_interaction_nba_id"), ["nba_id"], unique=False)
        batch_op.create_index(
            "ix_interaction_target", ["target_type", "target_id", "int_ts"], unique=False
        )

    op.create_table(
        "message_draft",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nba_id", sa.Integer(), nullable=False),
        sa.Column("variant_no", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("is_selected", sa.Boolean(), nullable=False),
        sa.Column("edited_by_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["edited_by_user_id"], ["user.id"], name=op.f("fk_message_draft_edited_by_user_id_user")
        ),
        sa.ForeignKeyConstraint(["nba_id"], ["nba.id"], name=op.f("fk_message_draft_nba_id_nba")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_draft")),
    )
    with op.batch_alter_table("message_draft", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_message_draft_nba_id"), ["nba_id"], unique=False)

    op.create_table(
        "nba_candidate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=False),
        sa.Column("nba_id", sa.Integer(), nullable=True),
        sa.Column("target_type", sa.String(length=8), nullable=False),
        sa.Column("target_id", sa.String(length=16), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("content_id", sa.String(length=16), nullable=True),
        sa.Column("eligible", sa.Boolean(), nullable=False),
        sa.Column("gate_failures", sa.JSON(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_id"], ["content.content_id"], name=op.f("fk_nba_candidate_content_id_content")
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"], ["engine_cycle.id"], name=op.f("fk_nba_candidate_cycle_id_engine_cycle")
        ),
        sa.ForeignKeyConstraint(["nba_id"], ["nba.id"], name=op.f("fk_nba_candidate_nba_id_nba")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nba_candidate")),
    )
    with op.batch_alter_table("nba_candidate", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_nba_candidate_nba_id"), ["nba_id"], unique=False)
        batch_op.create_index(
            "ix_nba_candidate_target", ["cycle_id", "target_type", "target_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nba_candidate", schema=None) as batch_op:
        batch_op.drop_index("ix_nba_candidate_target")
        batch_op.drop_index(batch_op.f("ix_nba_candidate_nba_id"))

    op.drop_table("nba_candidate")
    with op.batch_alter_table("message_draft", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_message_draft_nba_id"))

    op.drop_table("message_draft")
    with op.batch_alter_table("interaction", schema=None) as batch_op:
        batch_op.drop_index("ix_interaction_target")
        batch_op.drop_index(batch_op.f("ix_interaction_nba_id"))

    op.drop_table("interaction")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_ts"))
        batch_op.drop_index(batch_op.f("ix_audit_log_nba_id"))

    op.drop_table("audit_log")
    with op.batch_alter_table("rep_hcp", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rep_hcp_hcp_id"))

    op.drop_table("rep_hcp")
    with op.batch_alter_table("nba", schema=None) as batch_op:
        batch_op.drop_index("ix_nba_target")
        batch_op.drop_index(batch_op.f("ix_nba_status"))
        batch_op.drop_index(batch_op.f("ix_nba_cycle_id"))

    op.drop_table("nba")
    with op.batch_alter_table("medication_fill", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_medication_fill_therapy_id"))
        batch_op.drop_index(batch_op.f("ix_medication_fill_patient_id"))

    op.drop_table("medication_fill")
    with op.batch_alter_table("content_review", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_content_review_content_id"))

    op.drop_table("content_review")
    with op.batch_alter_table("care_manager_patient", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_care_manager_patient_patient_id"))

    op.drop_table("care_manager_patient")
    with op.batch_alter_table("adherence_snapshot", schema=None) as batch_op:
        batch_op.drop_index("ix_adherence_snapshot_therapy_asof")
        batch_op.drop_index(batch_op.f("ix_adherence_snapshot_patient_id"))

    op.drop_table("adherence_snapshot")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_role"))

    op.drop_table("user")
    with op.batch_alter_table("patient_therapy", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_patient_therapy_patient_id"))
        batch_op.drop_index(batch_op.f("ix_patient_therapy_measure"))

    op.drop_table("patient_therapy")
    with op.batch_alter_table("patient_hcp", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_patient_hcp_hcp_id"))

    op.drop_table("patient_hcp")
    with op.batch_alter_table("consent", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_consent_patient_id"))

    op.drop_table("consent")
    op.drop_table("sim_latent")
    with op.batch_alter_table("patient", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_patient_risk_segment"))

    op.drop_table("patient")
    with op.batch_alter_table("model_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_model_version_name"))

    op.drop_table("model_version")
    with op.batch_alter_table("hcp", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_hcp_specialty"))
        batch_op.drop_index(batch_op.f("ix_hcp_segment"))

    op.drop_table("hcp")
    op.drop_table("feature_snapshot")
    op.drop_table("engine_cycle")
    op.drop_table("engine_config")
    with op.batch_alter_table("content", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_content_mlr_status"))
        batch_op.drop_index(batch_op.f("ix_content_audience"))

    op.drop_table("content")
    # ### end Alembic commands ###
